
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feiaylnqnvjolwiipqdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlaWF5bG5xbnZqb2x3aWlwcWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTQxMzQsImV4cCI6MjA2MzQzMDEzNH0.HDa6LLL032fBEgb3F_AwDxCa1IGCKf6vK_CPJHTnK1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
